name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Thực hiện vào lúc 00:00 UTC mỗi ngày

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Make a dummy commit
        run: |
          echo "This is a dummy file" > dummy.txt  # Tạo tệp dummy.txt nếu chưa tồn tại
          echo "$(TZ='Asia/Ho_Chi_Minh' date) - Commit on $(TZ='Asia/Ho_Chi_Minh' date +%Y-%m-%d)" >> dummy.txt
          git config --global user.email "trantanphat08012004@gmail.com"  # Thay thế bằng email của bạn
          git config --global user.name "BeckPac"            # Thay thế bằng tên người dùng của bạn
          git add dummy.txt
          git commit -m "Daily commit" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/ttphat204/Daily_Commit.git main
