name: Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy vào lúc 00:00 UTC mỗi ngày

  push:
    branches:
      - main

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Sync with remote
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Make a dummy commit
        run: |
          echo "This is a dummy file" > dummy.txt
          echo "$(TZ='Asia/Ho_Chi_Minh' date) - Commit on $(TZ='Asia/Ho_Chi_Minh' date +%Y-%m-%d)" >> dummy.txt
          git config --global user.email "trantanphat08012004@gmail.com"
          git config --global user.name "BeckPac"
          git add dummy.txt
          git commit -m "Daily commit" || echo "No changes to commit"

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/ttphat204/Daily_Commit.git main || echo "Push failed"
